export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_CODE: "SET_CODE",
  SET_SONG: "SET_SONG",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_THEME: "SET_THEME"
};
